# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solarapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('FI', models.BooleanField()),
                ('frequency', models.CharField(max_length=50)),
                ('standard', models.IntegerField()),
            ],
        ),
    ]
