# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('cell_technology', models.CharField(max_length=50)),
                ('cell_manufacturer', models.CharField(max_length=50)),
                ('number_of_cells', models.IntegerField()),
                ('number_of_cells_in_series', models.IntegerField()),
                ('number_of_series_strings', models.IntegerField()),
                ('number_of_diodes', models.IntegerField()),
                ('product_length', models.IntegerField()),
                ('product_width', models.IntegerField()),
                ('superstate_type', models.CharField(max_length=50)),
                ('superstate_manufacturer', models.CharField(max_length=50)),
                ('substrate_type', models.CharField(max_length=50)),
                ('substrate_manufacturer', models.CharField(max_length=50)),
                ('frame_type', models.CharField(max_length=50)),
                ('frame_adhesive', models.CharField(max_length=50)),
                ('encapsulate_type', models.CharField(max_length=50)),
                ('encapsulate_manufacturer', models.CharField(max_length=50)),
                ('junction_box_type', models.CharField(max_length=50)),
                ('junction_box_manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
